---
- name: Setup Rancher on Ubuntu
  hosts: all
  become: yes
  vars:
    docker_url: "https://get.docker.com"
    rancher_image: "rancher/rancher"
    rancher_port_http: 80
    rancher_port_https: 443
    rancher_ip: "{{ ansible_default_ipv4.address }}"

  tasks:

    - name: Update and upgrade Ubuntu packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Install OpenSSH Server
      apt:
        name: openssh-server
        state: present

    - name: Install cURL
      apt:
        name: curl
        state: present

    - name: Check cURL version
      command: curl --version
      register: curl_version
      changed_when: false

    - debug:
        msg: "Installed cURL version: {{ curl_version.stdout_lines[0] }}"

    - name: Install required dependencies for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Docker GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null
        chmod a+r /etc/apt/keyrings/docker.asc
      args:
        executable: /bin/bash

    - name: Add Docker repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Pull Rancher Docker Container
      command: docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
      args:
        creates: "/var/lib/docker/containers"

    - name: Get Rancher container ID
      shell: "docker ps --filter 'ancestor=rancher/rancher' --format '{{ '{{' }}.ID{{ '}}' }}'"
      register: rancher_container_id
      changed_when: false

    - name: Get Rancher bootstrap password
      shell: "docker logs {{ rancher_container_id.stdout }} 2>&1 | grep 'Bootstrap Password:' | awk '{print $NF}'"
      register: rancher_password
      changed_when: false

    - name: Print Rancher bootstrap password
      debug:
        msg: "Rancher Bootstrap Password: {{ rancher_password.stdout }}"

    - name: Open Rancher in browser
      debug:
        msg: "Open Rancher in your browser: http://{{ ansible_default_ipv4.address }}"

    - name: Install Rancher compatible Docker
      shell: "curl -fsSL {{ docker_url }} | sh"
      args:
        creates: /usr/bin/docker

    - name: Refresh group membership
      shell: newgrp docker
      changed_when: false

    - name: Pull Rancher Docker image
      docker_image:
        name: "{{ rancher_image }}"
        source: pull

    - name: Run Rancher container
      docker_container:
        name: rancher
        image: "{{ rancher_image }}"
        state: started
        restart_policy: unless-stopped
        privileged: yes
        ports:
          - "{{ rancher_port_http }}:80"
          - "{{ rancher_port_https }}:443"

    - name: Wait for Rancher to initialize
      pause:
        minutes: 1

    - name: Get Rancher container ID
      command: docker ps --filter "ancestor={{ rancher_image }}" --format "{{'{{.ID}}'}}"
      register: rancher_container_id
      changed_when: false

    - debug:
        msg: "Rancher container ID: {{ rancher_container_id.stdout }}"

    - name: Get Rancher bootstrap password
      command: docker exec {{ rancher_container_id.stdout }} cat /var/lib/rancher/k3s/server/node-token
      register: bootstrap_password
      changed_when: false

    - debug:
        msg: "Rancher bootstrap password: {{ bootstrap_password.stdout }}"

    - name: Open Rancher in browser
      debug:
        msg: "Open Rancher in your browser: http://{{ rancher_ip }}"
